# Generated by Django 4.1 on 2022-09-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo_app', '0002_produto_pessoa_criador_dispositivo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria_tipo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Variedades'), (2, 'Comida'), (3, 'Brinquedo')], null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
